//=================================================================================
// ------ Help message on the screen ------
//=================================================================================

if(help)
 {
 cout <<
 "                                                                              \n"
 "===================================================================           \n"
 "                ---Help on flags used for PSD---                              \n"
 "===================================================================           \n"
 "                                                                              \n"
 "                                                                              \n"
 " ---------------------------------------------------------------------------- \n"
 "                                                                              \n"
 "  -dirichletpointconditions [int]  Number of Dirchlet points.                 \n"
 "                                   Default 1.                                 \n"
 "                                                                              \n"
 "  -dirichletconditions      [int]  Number of Dirchlet boundaries.             \n"
 "                                   Default 1.                                 \n"
 "                                                                              \n"
 "  -tractionconditions       [int]  Number of Neumann or traction boundaries.  \n"
 "                                   Default 1.                                 \n"
 "                                                                              \n"
 "  -parmetis_worker          [int]  Active when mesh partitioner is parmetis.  \n"
 "                                   Default MPI size.                          \n"
 "                                                                              \n"
 "  -dimension                [int]  Dimension of  problem. 2 for 2D 3 for 3D.  \n"
 "                                   Default 2.                                 \n"
 "                                                                              \n"
 "  -lagrange                 [int]  Lagrange order used for building FE space. \n"
 "                                   Option  1 for P1 or 2 for P2. Default 1.   \n"
 "                                                                              \n"
 "  ----------------------------------------------------------------------------\n"
 "                                                                              \n"
 "  -doublecouple    [string] Soil  dynamics  double couple bounday condition.  \n"
 "                            Use  force-based|displacement-based.              \n"
 "                                                                              \n"
 "  -nonlinearmethod [string] Nonlinear solving method type.                    \n"
 "                            Use Picard|Newton-Raphsons.                       \n"
 "                                                                              \n"
 "  -partitioner     [string] Mesh partitioner to use for domain-decomposition. \n"
 "                            Use metis|scotch|parmetis.                        \n"
 "                                                                              \n"
 "  -postprocess     [string] Indicate postprocessing quantity.                 \n"
 "                            Use u|v|a|phi|uphi|uva.                           \n"
 "                                                                              \n"
 "  -problem         [string] Interested problem to be solved by PSD.           \n"
 "                            Use linear-elasticity|damage|elastodynamics.      \n"
 "                                                                              \n"
 "  -model           [string] Interested model by which the problem is colved.  \n"
 "                            Use hybrid-phase-field|Mazar.                     \n"
 "                                                                              \n"
 "  ----------------------------------------------------------------------------\n"
 "                                                                              \n"
 "  -help         [bool]     To activate helping message on the terminal.       \n"
 "                                                                              \n"
 "  -plot         [bool]     To activate plotting routine.                      \n"
 "                                                                              \n"
 "  -debug        [bool]     To activate debug openGL plotting routine.         \n"
 "                                                                              \n"
 "  -useGFP       [bool]     To activate use of GoFastPlugins.                  \n"
 "                                                                              \n"
 "  -timelog      [bool]     To setup time logging for various phases of solver.\n"
 "                                                                              \n"
 "  -useRCM       [bool]     To activate renumbering via Reverse Cuthill Mckee. \n"
 "                                                                              \n"
 "  -pipegnu      [bool]     To activate realtime pipe plotting using GnuPlot.  \n"
 "                                                                              \n"
 "  -bodyforce    [bool]     To activate volumetric source term (body force).   \n"
 "                                                                              \n"
 "  -vectorial    [bool]     To generate vectorial space solver for non-linear. \n"
 "                                                                              \n"
 "  -supercomp    [bool]     To be used when using a cluster/supercomputer.     \n"
 "                                                                              \n"
 "  -fastmethod   [bool]     Fast method for linear elasticity.                 \n"
 "                                                                              \n"
 "  -energydecomp [bool]     To activate hybrid phase field energy decomposition.\n"
 "                                                                              \n"
 "  -sequential   [bool]     To generate a sequential ff++ solver.              \n"
 "                                                                              \n";


} //-- [if loop terminator] help ended --//

