//=================================================================================
// ------ Help message on the screen ------
//=================================================================================

if(help)
 {
 cout <<
 "                                                                              \n"
 "==============================================================================\n"
 "                                                                              \n"
 "                        --- Help on flags used for ---                        \n"
 "                                PSD_PreProcess                                \n"
 "                                                                              \n"
 "==============================================================================\n"
 "                                                                              \n"
 "                                                                              \n"
 " ---------------------------------------------------------------------------- \n"
 "          INTEGER type flags, these flags expect an integer value             \n"
 " ---------------------------------------------------------------------------- \n"
 "                                                                              \n"
 "                                                                              \n"
 "  -dirichletpointconditions [int]     Number of Dirichlet points.             \n"
 "                                      Default 1.                              \n"
 "                                                                              \n"
 "  -bodyforceconditions      [int]     Number of regions in which body force   \n"
 "                                      is define.  Default 0.                  \n"
 "                                                                              \n"
 "  -dirichletconditions      [int]     Number of Dirichlet boundaries.         \n"
 "                                      Default 1.                              \n"
 "                                                                              \n"
 "  -tractionconditions       [int]     Number of Neumann or traction boundaries\n"
 "                                      Default 1.                              \n"
 "                                                                              \n"
 "  -parmetis_worker          [int]     Number of workers for mesh partitioner  \n"
 "                                      parMETIS. Default MPI size.             \n"
 "                                                                              \n"
 "  -dimension                [int]     Dimension of  problem. 2 for 2D 3 for 3D\n"
 "                                      Default 2.                              \n"
 "                                                                              \n"
 "  -lagrange                 [int]     Lagrange order for building FE space.   \n"
 "                                      Option  1 for P1 or 2 for P2. Default 1.\n"
 "                                                                              \n"
 "                                                                              \n"
 " ---------------------------------------------------------------------------- \n"
 "          STRING type flags, these flags expect an string value               \n"
 " ---------------------------------------------------------------------------- \n"
 "                                                                              \n"
 "                                                                              \n"
 "  -timediscretization [string]     Time discretization type. Use any either   \n"
 "                                   generalized-alpha | newmark-beta           \n"
 "                                                                              \n"
 "  -nonlinearmethod    [string]     Nonlinear solving method type.             \n"
 "                                   Use Picard | Newton-Raphsons.              \n"
 "                                                                              \n"
 "  -reactionforce      [string]     Reaction force calculation method.         \n"
 "                                   Use stress-based | variational-based.      \n"
 "                                                                              \n"
 "  -doublecouple       [string]     Soildynamics  doublecouple boundary cond.  \n"
 "                                   Use  force-based | displacement-based.     \n"
 "                                                                              \n"
 "  -partitioner        [string]     Mesh partitioner to be used.               \n"
 "                                   Use metis | scotch | parmetis.             \n"
 "                                                                              \n"
 "  -postprocess        [string]     Indicate postprocessing quantity. Use one  \n"
 "                                   u | v | a | ua | uv | va | phi | uphi | uva\n"
 "                                                                              \n"
 "  -problem            [string]     Interested problem to be solved by PSD.    \n"
 "                                   linear-elasticity | damage | elastodynamics\n"
 "                                   | soildynamics.                            \n"
 "                                                                              \n"
 "  -model              [string]     Model by which the problem is solved.      \n"
 "                                   Use hybrid-phase-field | pseudononlinear   \n"
 "                                   | Mazar                                    \n"
 "                                                                              \n"
 "                                                                              \n"
 " ---------------------------------------------------------------------------- \n"
 "       BOOLEAN type flags, these flags are like activaction switches          \n"
 " ---------------------------------------------------------------------------- \n"
 "                                                                              \n"
 "                                                                              \n"
 "  -help              [bool]     To activate helping message on the terminal.  \n"
 "                                Default false.                                \n"
 "                                                                              \n" 
 "  -plot              [bool]     To activate plotting routine.                 \n"
 "                                Default false.                                \n" 
 "                                                                              \n"
 "  -debug             [bool]     To activate debug openGL plotting routine.    \n"
 "                                Default false.                                \n" 
 "                                                                              \n"
 "  -useGFP            [bool]     To activate use of GoFastPlugins.             \n"
 "                                Default true/false.                           \n" 
 "                                                                              \n"
 "  -timelog           [bool]     To setup time logging for various phases of   \n"
 "                                solver. Default false.                        \n" 
 "                                                                              \n"
 "  -useRCM            [bool]     To activate mesh level renumbering via        \n"
 "                                Reverse Cuthill Mckee. Default false.         \n"  
 "                                                                              \n"
 "  -pipegnu           [bool]     To activate realtime pipe plotting using      \n"
 "                                GnuPlot. Default false.                       \n"  
 "                                                                              \n"
 "  -bodyforce         [bool]     Activate volumetric source term (body force)  \n"
 "                                Default false.                                \n"  
 "                                                                              \n"
 "  -vectorial         [bool]     To generate vectorial space solver for        \n"
 "                                nonlinear damage. Default false.              \n"  
 "                                                                              \n"
 "  -supercomp         [bool]     To be used when using a cluster/supercomputer \n"
 "                                Default false.                                \n"     
 "                                                                              \n"
 "  -energydecomp      [bool]     To activate hybrid phase field energy         \n"
 "                                splitting/decomposition. Default false.       \n"   
 "                                                                              \n"
 "  -sequential        [bool]     To generate a sequential PSD solver.          \n"
 "                                Default false.                                \n"
 "                                                                              \n" 
 "  -pointprobe        [bool]     To insert point probes for post processing.   \n"
 "                                Default false.                                \n"   
 "                                                                              \n"
 "  -top2vol-meshing   [bool]     Activate top-ii-vol point source meshing for  \n" 
 "                                soil-dynamics. Default false.                 \n" 
 "                                                                              \n" 
 "  -constrainHPF      [bool]     Activate constrain condition for damage for   \n"
 "                                the hybrid phase-field model.                 \n"
 "                                                                              \n"
 "  -getreactionforce  [bool]     Activate routine for extraction of reactions  \n"
 "                                at surface.                                   \n"
 "                                                                              \n" 
 "  -plotreactionforce [bool]     Activate real time pipe plotting via GnuPlot  \n"
 "                                Default false.                                \n"
 "                                                                              \n"
 "  -withmaterialtensor [bool]    Generate variational formulation that includes\n"
 "                                material tensor. Default false.               \n"    
 "                                                                              \n" 
 "  -crackdirichletcondition [bool] Activate pre-cracked surface Dirichlet for  \n"
 "                                  the hybrid phase-field model. Default false \n" 
 "                                                                              \n"
 "                                                                              \n" 
 "==============================================================================\n"
 "                                                                              \n"
 "                        --- Help on flags used for ---                        \n"
 "                                   PSD_Solve                                  \n"
 "                                                                              \n"
 "==============================================================================\n"
 "                                                                              \n"
 "                                                                              \n"
 " ---------------------------------------------------------------------------- \n"
 "          INTEGER type flags, these flags expect an integer value             \n"
 " ---------------------------------------------------------------------------- \n"
 "                                                                              \n"
 "  -np         [int]     Number of processes to use for parallelization        \n"
 "                        Default 2. Values  accepted 1 to infinity             \n" 
 "                                                                              \n"
 "  -v          [int]     Verbosity of the background FEM kernel. Default 1.    \n"
 "                        Set 0 for no output. Values  accepted 0 to infinity   \n" 
 "                                                                              \n"
 "  -split      [int]     Split uniformly the mesh. Default 1 = no splitting.   \n"
 "                        Use 2 to split once. Values  accepted 2 to 12.        \n"
 "                                                                              \n"
 "  -ksp_max_it [int]     PETSc flag to choose  Krylov solver max iterations.   \n"
 "                        Default 1000.                                         \n"
 "                                                                              \n"
 "                                                                              \n"
 " ---------------------------------------------------------------------------- \n"
 "       REAL type flags, these flags expect an floating point (real) value     \n"
 " ---------------------------------------------------------------------------- \n"
 "                                                                              \n"
 "  -ksp_atol  [real]     PETSc flag to set  absolute tolerance for the Krylov  \n"
 "                        solver convergence. Default 1e-5.                     \n" 
 "                                                                              \n"
 "  -ksp_rtol  [real]     PETSc flag to set  relative tolerance for the Krylov  \n"
 "                        solver. Default 1e-5.                                 \n" 
 "                                                                              \n"
 " ---------------------------------------------------------------------------- \n"
 "       BOOLEAN type flags, these flags are like activaction switches          \n"
 " ---------------------------------------------------------------------------- \n"
 "                                                                              \n"
 "  -wg        [bool]     To activate with graphics option for OpenGL graphics  \n"
 "                        Default false.                                        \n"
 "                                                                              \n"
 " ---------------------------------------------------------------------------- \n"
 "          STRING type flags, these flags expect an string value               \n"
 " ---------------------------------------------------------------------------- \n"
 "                                                                              \n"
 "  -mesh        [string]     Mesh file to be used. Either use .mesh or .msh    \n"
 "                            e.g., -mesh nameofmesh.mesh                       \n"
 "                                                                              \n"
 "  -ksp_type    [string]     PETSc flag to choose the Krylov solver. Default cg\n"
 "                            Use cg | gmres | bicg | bicgstab.                 \n"
 "                                                                              \n"
 "  -pc_type     [string]     PETSc flag to choose preconditioner for the solver\n"
 "                            Default bjacobi. Use jacobi | bjacobi | lu | gamg \n"
 "                                                                              \n"
 "  -sub_pc_type [string]     PETSc flag to choose sub preconditioner for solver\n"
 "                            Default ilu. Use ilu | icc | lu | gamg .          \n"
 "                                                                              \n";

  
} //-- [if loop terminator] help ended --//

