documents: fast-track-tutorials tutorial-L-shape-cracking

fast-track-tutorials: fast-track-tutorials.pdf

fast-track-tutorials.pdf: fast-track-tutorials.md
	pandoc -s -i fast-track-tutorials.md -o fast-track-tutorials.pdf

tutorial-L-shape-cracking: tutorial-L-shape-cracking.pdf

tutorial-L-shape-cracking.pdf: tutorial-L-shape-cracking.md
	pandoc -s -i tutorial-L-shape-cracking.md -o tutorial-L-shape-cracking.pdf
