documents: fast-track-tutorials tutorial-1 tutorial-2 tutorial-3

fast-track-tutorials: fast-track-tutorials.pdf

fast-track-tutorials.pdf: fast-track-tutorials.md
	pandoc -s -i fast-track-tutorials.md -o fast-track-tutorials.pdf

tutorial-1: tutorial-1.pdf

tutorial-1.pdf: tutorial-1.md
	pandoc -s -i tutorial-1.md -o tutorial-1.pdf

tutorial-2: tutorial-2.pdf

tutorial-2.pdf: tutorial-2.md
	pandoc -s -i tutorial-2.md -o tutorial-2.pdf

tutorial-3: tutorial-3.pdf

tutorial-3.pdf: tutorial-3.md
	pandoc -s -i tutorial-3.md -o tutorial-3.pdf
