.PHONY: usage clean cleanvtu 

help: usage

usage:
	@echo ""
	@echo "USAGE: "
	@echo ""
	@echo "clean    - Clears all the unwanted files"
	@echo "cleanvtu - Clears all post-preocessed files"
	@echo ""


clean:
	rm *.pvd VTUs/* Mesh.edp Main.edp Macros.edp VariationalFormulations.edp BoundaryAndSourceConditions.edp LinearFormBuilderAndSolver.edp Parameters.edp PostProcessor.edp MeshPartitioning.edp
 
cleanvtu:
	rm *.pvd VTUs/*


