.PHONY: usage clean cleanvtu 

help: usage

usage:
	@echo ""
	@echo "USAGE: "
	@echo ""
	@echo "clean    - Clears all the unwanted files"
	@echo "cleanvtu - Clears all post-preocessed files"
	@echo ""


clean:
	rm *.pvd VTUs/* mesh.edp main.edp macros.edp varfmatsolve.edp meshPartitioning.edp parameters.edp

cleanvtu:
	rm *.pvd VTUs/*


